/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arsipsuratlk;

import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author HP
 */
public class pageLogin extends javax.swing.JFrame {

    /**
     * Creates new form pageLogin
     */
    public pageLogin() {
        initComponents();
        labelimage.setBorder(new EmptyBorder(0,0,0,0));
        enterButton.setBorder(null);
        enterButton.setContentAreaFilled(false);
        enterButton.setVisible(true);
        usernameTextField.setText("Username");
        usernameTextField.setForeground(new Color(153,153,153));
        passwordTextField.setText("Password");
        passwordTextField.setForeground(new Color(153,153,153));
        usernameAlert.setText(" ");
        passwordAlert.setText(" ");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        labelimage = new javax.swing.JLabel();
        iconFTI = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        passwordTextField = new javax.swing.JTextField();
        enterButton = new javax.swing.JButton();
        usernameAlert = new javax.swing.JLabel();
        passwordAlert = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        disiniButton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(220, 221, 216));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        labelimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arsipsuratlk/img/login_1.jpg"))); // NOI18N
        labelimage.setText(" ");

        iconFTI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arsipsuratlk/img/logo_fti_50x50.png"))); // NOI18N
        iconFTI.setText(" ");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arsipsuratlk/img/icon_idpass.jpg"))); // NOI18N
        jLabel1.setText(" ");

        usernameTextField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        usernameTextField.setText("Username");
        usernameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameTextFieldFocusLost(evt);
            }
        });

        passwordTextField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        passwordTextField.setText("Password");
        passwordTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordTextFieldFocusLost(evt);
            }
        });

        enterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arsipsuratlk/img/icon_enter.jpg"))); // NOI18N
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });

        usernameAlert.setForeground(new java.awt.Color(255, 51, 51));

        passwordAlert.setForeground(new java.awt.Color(255, 51, 51));

        jLabel2.setText("Tidak punya akun?daftar");

        disiniButton.setForeground(new java.awt.Color(51, 51, 255));
        disiniButton.setText("di sini");
        disiniButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                disiniButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(labelimage, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(disiniButton))
                            .addComponent(enterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(usernameAlert)
                                    .addComponent(passwordAlert)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(iconFTI)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelimage, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(usernameAlert)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(iconFTI)
                        .addGap(67, 67, 67)
                        .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordAlert)
                .addGap(55, 55, 55)
                .addComponent(enterButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(disiniButton))
                .addContainerGap(158, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTextFieldFocusGained
        if(usernameTextField.getText().equals("Username")){
            usernameTextField.setText("");
            usernameTextField.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_usernameTextFieldFocusGained

    private void usernameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTextFieldFocusLost
        if(usernameTextField.getText().equals("")){
            usernameTextField.setText("Username");
            usernameTextField.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_usernameTextFieldFocusLost

    private void passwordTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTextFieldFocusGained
        if(passwordTextField.getText().equals("Password")){
            passwordTextField.setText("");
            passwordTextField.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_passwordTextFieldFocusGained

    private void passwordTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTextFieldFocusLost
        if(passwordTextField.getText().equals("")){
            passwordTextField.setText("Password");
            passwordTextField.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_passwordTextFieldFocusLost

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
       if(usernameTextField.getText().equals("Username")&&passwordTextField.getText().equals("Password")){
           JOptionPane.showMessageDialog(this,"Isi data terlebih dahulu");
       }else if(usernameTextField.getText().equals("Username")){
           JOptionPane.showMessageDialog(this,"Lengkapi data terlebih dahulu");
       }else if(passwordTextField.getText().equals("Password")){
           JOptionPane.showMessageDialog(this,"Lengkapi data terlebih dahulu");
       }else{
           //
       }
        //Root Version
        if(usernameTextField.getText().equals("admin")&&passwordTextField.getText().equals("12345")){
            JOptionPane.showMessageDialog(null,"Login Berhasil");
            UserInterface ed=new UserInterface();
            ed.setExtendedState(JFrame.MAXIMIZED_BOTH);
            ed.setVisible(true);
            this.dispose();
        }
        try{
        com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/arsip_lk","root", "");
        ResultSet rs = koneksi.createStatement().executeQuery("select * from db_data");
            while(rs.next()){
                if(usernameTextField.getText().equals(rs.getString(1))&&passwordTextField.getText().equals(rs.getString(2))){
                    //JOptionPane.showMessageDialog(null,"Login Berhasil");        
                    reset();
                    UserInterface ed=new UserInterface();
                    ed.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    ed.setVisible(true);
                    this.dispose();
                }//else{
                //JOptionPane.showMessageDialog(this,"Data Tidak Diketahui");
                //}
            }
        }catch(SQLException e){
            System.out.println("enterbuttoneror");
            Logger.getLogger(UserInterface.class.getName()).log(Level.SEVERE, null, e);
        }
        
  
        
    }//GEN-LAST:event_enterButtonActionPerformed

    private void disiniButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disiniButtonMouseClicked
        SignUp ed=new SignUp();
        ed.setExtendedState(JFrame.MAXIMIZED_BOTH);
        ed.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_disiniButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pageLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pageLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pageLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pageLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pageLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel disiniButton;
    private javax.swing.JButton enterButton;
    private javax.swing.JLabel iconFTI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelimage;
    private javax.swing.JLabel passwordAlert;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JLabel usernameAlert;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables

    private void reset() {
        usernameTextField.setText("Username");
        usernameTextField.setForeground(new Color(153,153,153));
        passwordTextField.setText("Password");
        passwordTextField.setForeground(new Color(153,153,153));
    }

}
