/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arsipsuratlk;

import arsipsuratlk.pageLogin;
import com.mysql.jdbc.Connection;
import java.awt.Color;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;


/**
 *
 * @author edwindtr_
 */
public class UserInterface extends javax.swing.JFrame {
            
    String jeniskodesurat;
    String keterangancombobox;
    String kodesurat;
    String bulan;
    String universitas;
    int kodesuratnomor;
    DefaultTableModel model;
    
    public UserInterface() {
        initComponents();
        //Isi row tabel pada kolom 0
        String [] judul = {"Surat Ke-","Jenis Nomor Surat","Perihal","Fakultas","Universitas","Bulan","Tahun","Keterangan"};
        model = new DefaultTableModel (judul, 0);
        tabelSurat.setModel(model);
        mainPanel.setBorder(new EmptyBorder(0,0,0,0));
        tampilkanData();
        lebarKolom();  
        //Note
        System.out.println("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        nomorSuratText = new javax.swing.JTextField();
        jenisKodeSuratText = new javax.swing.JTextField();
        perihalText = new javax.swing.JTextField();
        fakultasText = new javax.swing.JTextField();
        universitasText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelSurat = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        simpanButton = new javax.swing.JButton();
        hapusButton = new javax.swing.JButton();
        tambahButton = new javax.swing.JButton();
        gantiButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        logOutButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        cariBerdasarkanNomorSuratText = new javax.swing.JTextField();
        cariBerdasarkanNomorSuratButton = new javax.swing.JButton();
        cariBerdasarkanJenisKodeSuratText = new javax.swing.JTextField();
        cariBerdasarkanKodeSuratButton = new javax.swing.JButton();
        cariBerdasarkanUniversitasText = new javax.swing.JTextField();
        cariBerdasarkanUniversitasButton = new javax.swing.JButton();
        cariBerdasarkanKeteranganText = new javax.swing.JTextField();
        cariBerdasarkanKeteranganButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bulanText = new javax.swing.JTextField();
        tahunText = new javax.swing.JTextField();
        keteranganComboBox = new javax.swing.JComboBox();
        formatText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tanggalSuratText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ARSIP SURAT LK");
        setUndecorated(true);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        nomorSuratText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nomorSuratText.setForeground(new java.awt.Color(153, 153, 153));
        nomorSuratText.setText("Nomor Surat");
        nomorSuratText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nomorSuratTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomorSuratTextFocusLost(evt);
            }
        });

        jenisKodeSuratText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jenisKodeSuratText.setForeground(new java.awt.Color(153, 153, 153));
        jenisKodeSuratText.setText("Jenis Kode Surat");
        jenisKodeSuratText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jenisKodeSuratTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jenisKodeSuratTextFocusLost(evt);
            }
        });

        perihalText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        perihalText.setForeground(new java.awt.Color(153, 153, 153));
        perihalText.setText("Perihal");
        perihalText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                perihalTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                perihalTextFocusLost(evt);
            }
        });

        fakultasText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fakultasText.setForeground(new java.awt.Color(153, 153, 153));
        fakultasText.setText("Fakultas");
        fakultasText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fakultasTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fakultasTextFocusLost(evt);
            }
        });

        universitasText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        universitasText.setForeground(new java.awt.Color(153, 153, 153));
        universitasText.setText("Universitas");
        universitasText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                universitasTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                universitasTextFocusLost(evt);
            }
        });

        tabelSurat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tabelSurat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Surat Ke-", "Jenis Kode Surat", "Perihal", "Fakultas", "Universitas", "Bulan", "Tahun", "Keterangan"
            }
        ));
        tabelSurat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelSuratMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelSurat);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        simpanButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        simpanButton.setText("Simpan");
        simpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanButtonActionPerformed(evt);
            }
        });

        hapusButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hapusButton.setText("Hapus");
        hapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusButtonActionPerformed(evt);
            }
        });

        tambahButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tambahButton.setText("Tambah");
        tambahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahButtonActionPerformed(evt);
            }
        });

        gantiButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        gantiButton.setText("Ganti");
        gantiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gantiButtonActionPerformed(evt);
            }
        });

        jPanel5.setForeground(new java.awt.Color(204, 204, 204));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arsipsuratlk/logo.jpg"))); // NOI18N
        jLabel3.setText(" ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        logOutButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        logOutButton.setText("Log Out");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        exitButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gantiButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tambahButton, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(hapusButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(simpanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(logOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(simpanButton)
                .addGap(18, 18, 18)
                .addComponent(hapusButton)
                .addGap(18, 18, 18)
                .addComponent(tambahButton)
                .addGap(18, 18, 18)
                .addComponent(gantiButton)
                .addGap(18, 18, 18)
                .addComponent(logOutButton)
                .addGap(18, 18, 18)
                .addComponent(exitButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        cariBerdasarkanNomorSuratText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cariBerdasarkanNomorSuratText.setForeground(new java.awt.Color(153, 153, 153));
        cariBerdasarkanNomorSuratText.setText("Cari Berdasarkan Nomor Surat");
        cariBerdasarkanNomorSuratText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cariBerdasarkanNomorSuratTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cariBerdasarkanNomorSuratTextFocusLost(evt);
            }
        });

        cariBerdasarkanNomorSuratButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cariBerdasarkanNomorSuratButton.setText("CARI");
        cariBerdasarkanNomorSuratButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariBerdasarkanNomorSuratButtonActionPerformed(evt);
            }
        });

        cariBerdasarkanJenisKodeSuratText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cariBerdasarkanJenisKodeSuratText.setForeground(new java.awt.Color(153, 153, 153));
        cariBerdasarkanJenisKodeSuratText.setText("Cari Berdasarkan Jenis Kode Surat");
        cariBerdasarkanJenisKodeSuratText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cariBerdasarkanJenisKodeSuratTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cariBerdasarkanJenisKodeSuratTextFocusLost(evt);
            }
        });

        cariBerdasarkanKodeSuratButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cariBerdasarkanKodeSuratButton.setText("CARI");
        cariBerdasarkanKodeSuratButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariBerdasarkanKodeSuratButtonActionPerformed(evt);
            }
        });

        cariBerdasarkanUniversitasText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cariBerdasarkanUniversitasText.setForeground(new java.awt.Color(153, 153, 153));
        cariBerdasarkanUniversitasText.setText("Cari Berdasarkan Universitas");
        cariBerdasarkanUniversitasText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cariBerdasarkanUniversitasTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cariBerdasarkanUniversitasTextFocusLost(evt);
            }
        });

        cariBerdasarkanUniversitasButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cariBerdasarkanUniversitasButton.setText("CARI");
        cariBerdasarkanUniversitasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariBerdasarkanUniversitasButtonActionPerformed(evt);
            }
        });

        cariBerdasarkanKeteranganText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cariBerdasarkanKeteranganText.setForeground(new java.awt.Color(153, 153, 153));
        cariBerdasarkanKeteranganText.setText("Cari Berdasarkan Keterangan");
        cariBerdasarkanKeteranganText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cariBerdasarkanKeteranganTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cariBerdasarkanKeteranganTextFocusLost(evt);
            }
        });

        cariBerdasarkanKeteranganButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cariBerdasarkanKeteranganButton.setText("CARI");
        cariBerdasarkanKeteranganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariBerdasarkanKeteranganButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cariBerdasarkanKeteranganText)
                    .addComponent(cariBerdasarkanUniversitasText, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cariBerdasarkanJenisKodeSuratText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                    .addComponent(cariBerdasarkanNomorSuratText, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cariBerdasarkanNomorSuratButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cariBerdasarkanKodeSuratButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cariBerdasarkanUniversitasButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cariBerdasarkanKeteranganButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cariBerdasarkanNomorSuratText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cariBerdasarkanNomorSuratButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cariBerdasarkanJenisKodeSuratText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cariBerdasarkanKodeSuratButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cariBerdasarkanUniversitasText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cariBerdasarkanUniversitasButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cariBerdasarkanKeteranganText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cariBerdasarkanKeteranganButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ARSIP");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("SURAT LK");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(43, 43, 43)))
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel4.setText("KBM PEDES SENIN @Copyright 2021");

        bulanText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bulanText.setForeground(new java.awt.Color(153, 153, 153));
        bulanText.setText("Bulan");
        bulanText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bulanTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                bulanTextFocusLost(evt);
            }
        });

        tahunText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tahunText.setForeground(new java.awt.Color(153, 153, 153));
        tahunText.setText("Tahun");
        tahunText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tahunTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tahunTextFocusLost(evt);
            }
        });

        keteranganComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        keteranganComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Umum", "Surat Peringatan\t", "Surat Keterangan", "Pendelegasian Wewenang" }));

        formatText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        formatText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formatTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                formatTextFocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Format Surat :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        tanggalSuratText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tanggalSuratText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tanggalSuratTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tanggalSuratTextFocusLost(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1135, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomorSuratText, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(perihalText, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jenisKodeSuratText, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fakultasText, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(universitasText, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bulanText, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tahunText, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(keteranganComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(formatText, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tanggalSuratText, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(473, 473, 473))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomorSuratText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(universitasText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jenisKodeSuratText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bulanText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(perihalText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tahunText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fakultasText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(keteranganComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formatText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(tanggalSuratText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Button Simpan
    private void simpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanButtonActionPerformed
        try{
            Connection koneksi = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/arsip_lk","root", "");
            ResultSet rs = koneksi.createStatement().executeQuery("select * from suratlk");
            while(rs.next()){
                if(nomorSuratText.getText().equals(rs.getString(1))&&jenisKodeSuratText.getText().equals(rs.getString(2))&&perihalText.getText().equals(rs.getString(3))&&fakultasText.getText().equals(rs.getString(4))&&universitasText.getText().equals(rs.getString(5))&&bulanText.getText().equals(rs.getString(6))&&tahunText.getText().equals(rs.getString(7))&&keteranganComboBox.getSelectedItem().equals(rs.getString(8))){
                JOptionPane.showMessageDialog(this, "Perbarui data yang akan disimpan");
                }else if(nomorSuratText.getText().equals(rs.getString(1))){
                    JOptionPane.showMessageDialog(this,"Tidak dapat duplikat nomor surat");
                }
            }
        } catch(SQLException ex) {
            System.out.println("Tidak Dapat Menduplikat Nomor Surat!!!");
        }
        //Try Catch Koneksi Ke Database
        try {
            Connection koneksi = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/arsip_lk","root", "");
            koneksi.createStatement().executeUpdate("insert into suratlk values" + "('"+nomorSuratText.getText()+"','"+jenisKodeSuratText.getText()+"','"+perihalText.getText()+"','"+fakultasText.getText()+"','"+universitasText.getText()+"', '"+bulanText.getText()+"','"+tahunText.getText()+"','"+keteranganComboBox.getSelectedItem()+"')");   
        } catch (SQLException ex) {
            System.out.println("Tidak Dapat Menduplikat Nomor Surat!!!");
            Logger.getLogger(UserInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
        //if(Logger.getLogger(UserInterface.class.getName()).log(Level.SEVERE, null, ex) == true){
        //    JOptionPane.showMessageDialog(this, "eror");
        //}
        //Pengkondisian Ada tidaknya value pada textfield
            //Prompt
            
            if(nomorSuratText.getText().equals("Nomor Surat")&&jenisKodeSuratText.getText().equals("Jenis Kode Surat")&&perihalText.getText().equals("Perihal")&&fakultasText.getText().equals("Fakultas")&&universitasText.getText().equals("Universitas")&&bulanText.getText().equals("Bulan")&&tahunText.getText().equals("Tahun")&&keteranganComboBox.getSelectedItem().equals("Umum")){
                JOptionPane.showMessageDialog(this, "Harap isi data terlebih dahulu");
            }else if(nomorSuratText.getText().equals("Nomor Surat")||jenisKodeSuratText.getText().equals("Jenis Kode Surat")||perihalText.getText().equals("Perihal")||fakultasText.getText().equals("Fakultas")||universitasText.getText().equals("Universitas")||bulanText.getText().equals("Bulan")||tahunText.getText().equals("Tahun")){
                JOptionPane.showMessageDialog(this, "Isi data dengan lengkap");
            }else{        
                tampilkanData();
                tampilkanTextFieldUtama();
                timpaWarnaBaruTexFieldFocus();
            }
    }//GEN-LAST:event_simpanButtonActionPerformed
//Button Ganti
    private void gantiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gantiButtonActionPerformed
        //Pengkondisian Duplikat Kode Surat(Primary Key)
        try{
            Connection koneksi = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/arsip_lk","root", "");
            ResultSet rs = koneksi.createStatement().executeQuery("select * from suratlk");
            while(rs.next()){
                if(nomorSuratText.getText().equals(rs.getString(1))&&jenisKodeSuratText.getText().equals(rs.getString(2))&&perihalText.getText().equals(rs.getString(3))&&fakultasText.getText().equals(rs.getString(4))&&universitasText.getText().equals(rs.getString(5))&&bulanText.getText().equals(rs.getString(6))&&tahunText.getText().equals(rs.getString(7))&&keteranganComboBox.getSelectedItem().equals(rs.getString(8))){
                JOptionPane.showMessageDialog(this, "Perbarui data yang akan diganti");
                }else if(nomorSuratText.getText().equals(rs.getString(1))){
                    JOptionPane.showMessageDialog(this,"Tidak dapat duplikat nomor surat");
                }
            }
        } catch(SQLException ex) {
            System.out.println("Tidak Dapat Menduplikat Nomor Surat!!!");
        }
        //Try Catch Koneksi Ke Database
        try {
            Connection koneksi = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/arsip_lk","root", "");
            koneksi.createStatement().executeUpdate("UPDATE suratlk SET JenisKodeSurat ='"+jenisKodeSuratText.getText()+"', Perihal = '"+perihalText.getText()+"', Fakultas = '"+fakultasText.getText()+"', Universitas = '"+universitasText.getText()+"',Bulan = '"+bulanText.getText()+"', Tahun ='"+tahunText.getText()+"', Keterangan = '"+keteranganComboBox.getSelectedItem()+"' WHERE NomorSurat = '"+nomorSuratText.getText()+"'");
        } catch (SQLException ex) {
            Logger.getLogger(UserInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
        //Pengkondisian Ada tidaknya value pada textfield
            //Prompt
            if(nomorSuratText.getText().equals("Nomor Surat")&&jenisKodeSuratText.getText().equals("Jenis Kode Surat")&&perihalText.getText().equals("Perihal")&&fakultasText.getText().equals("Fakultas")&&universitasText.getText().equals("Universitas")&&bulanText.getText().equals("Bulan")&&tahunText.getText().equals("Tahun")&&keteranganComboBox.getSelectedItem().equals("Umum")){
                JOptionPane.showMessageDialog(this, "Harap pilih data yang ingin diganti");
            }else if(nomorSuratText.getText().equals("Nomor Surat")||jenisKodeSuratText.getText().equals("Jenis Kode Surat")||perihalText.getText().equals("Perihal")||fakultasText.getText().equals("Fakultas")||universitasText.getText().equals("Universitas")||bulanText.getText().equals("Bulan")||tahunText.getText().equals("Tahun")){
                JOptionPane.showMessageDialog(this, "Harap pilih data yang ingin diganti");
            }     
            else{
                tampilkanData();
                tampilkanTextFieldUtama();
                timpaWarnaBaruTexFieldFocus();
            }
    }//GEN-LAST:event_gantiButtonActionPerformed
//Set Text dari tablerow ke setiap textfield
    private void tabelSuratMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelSuratMouseClicked
        int i = tabelSurat.getSelectedRow();
        if(i>-1){
            //menampilkan data ke textField
            //mengganti warna PlaceHolder ke warna Default
                //Nomor Surat Textfield
                nomorSuratText.setText(model.getValueAt(i, 0).toString());
                nomorSuratText.setForeground(new Color(0,0,0));
                nomorSuratText.setEditable(false);
                //Jenis Kode Surat Textfield
                jenisKodeSuratText.setText(model.getValueAt(i, 1).toString());
                jenisKodeSuratText.setForeground(new Color(0,0,0));
                //Perihal Textfield
                perihalText.setText(model.getValueAt(i, 2).toString());
                perihalText.setForeground(new Color(0,0,0));
                //Fakultas Textfield
                fakultasText.setText(model.getValueAt(i, 3).toString());
                fakultasText.setForeground(new Color(0,0,0));
                //Universitas Textfield
                universitasText.setText(model.getValueAt(i, 4).toString());
                universitasText.setForeground(new Color(0,0,0));
                //Bulans Textfield
                bulanText.setText(model.getValueAt(i, 5).toString());
                bulanText.setForeground(new Color(0,0,0));
                //Tahun Surat Textfield
                tahunText.setText(model.getValueAt(i, 6).toString());
                tahunText.setForeground(new Color(0,0,0));
                //Keterangan ComboBox
                keteranganComboBox.setSelectedItem(model.getValueAt(i, 7));
        }
        //Hapus Spasi Pada TextField Universitas
            universitas = model.getValueAt(i, 4).toString();
            universitas = universitas.replaceAll("\\s","");
        //Pengkondisian Format Surat Bagian Jenis Kode Surat
            switch (jenisKodeSuratText.getText()) {
                case "Internal Dalam":
                    jeniskodesurat = ("Int.d");
                    break;
                case "Internal Luar":
                    jeniskodesurat = ("Int.l");
                    break;
                case "Eksternal Dalam":
                    jeniskodesurat  = ("Eks.d");
                    break;
                case "Eksternal Luar":
                    jeniskodesurat  = ("Eks.l");
                    break;
                default:
                    jeniskodesurat  = ("Eror!");
                    break;
            }
        //Pengkondisian Jenis Surat Untuk Di Convert    
            if(keteranganComboBox.getSelectedItem().equals("Umum")){
                keterangancombobox = ("U");
            }else if(keteranganComboBox.getSelectedItem().equals("Surat Peringatan")){
                keterangancombobox = ("SP");
            }else if(keteranganComboBox.getSelectedItem().equals("Surat Keterangan")){
                keterangancombobox = ("Ket.");
            }else if(keteranganComboBox.getSelectedItem().equals("Pendelegasian Wewenang")){
                keterangancombobox = ("PW");
            }else{
                keterangancombobox = ("Eror!");
            }
        //Pengkondisian Kurang Dari 10
            kodesurat = nomorSuratText.getText();
            kodesuratnomor = Integer.parseInt(kodesurat);
                if(kodesuratnomor < 10){
                    kodesurat = ("0"+kodesuratnomor);
                }else if(kodesuratnomor >= 10){
                    kodesurat = (""+kodesuratnomor);
                }else{
                    kodesurat = ("Eror!");
                }
        //Pengkondisian Bulan Tahun
             switch (bulanText.getText()) {
            case "I":
                bulan = ("JANUARI");
                break;
            case "II":
                bulan = ("FEBUARI");
                break;
            case "III":
                bulan = ("MARET");
                break;
            case "IV":
                bulan = ("APRIL");
                break;
            case "V":
                bulan = ("MEI");
                break;
            case "VI":
                bulan = ("JUNI");
                break;
            case "VII":
                bulan = ("JULI");
                break;
            case "VIII":
                bulan = ("AGUSTUS");
                break;
            case "IX":
                bulan = ("SEPTEMBER");
                break;
            case "X":
                bulan = ("OKTOBER");
                break;
            case "XI":
                bulan = ("NOVEMBER");
                break;
            case "XII":
                bulan = ("DESEMBER");
                break;
            default:
                bulan  = ("Eror!");
                break;
            }
    //Deklarasi
        //SetText Format TextField
            formatText.setText(" "+kodesurat+"/"+ jeniskodesurat +"/"+ model.getValueAt(i, 2).toString() +"/"+ model.getValueAt(i, 3).toString()+"/"+ universitas +"/"+ keterangancombobox +"/"+ model.getValueAt(i, 5).toString()+"/"+ model.getValueAt(i, 6).toString());
            formatText.setEditable(false);
        //SetText TanggalSurat TextField
            tanggalSuratText.setText(" " + bulan + " - "+model.getValueAt(i, 6).toString());
            tanggalSuratText.setEditable(false);
    }//GEN-LAST:event_tabelSuratMouseClicked
//PlaceHolder untuk TextField Nomor Surat
    private void nomorSuratTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomorSuratTextFocusGained
        if(nomorSuratText.getText().equals("Nomor Surat")){
            nomorSuratText.setText("");
            nomorSuratText.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_nomorSuratTextFocusGained

    private void nomorSuratTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomorSuratTextFocusLost
        if(nomorSuratText.getText().equals("")){
            nomorSuratText.setText("Nomor Surat");
            nomorSuratText.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_nomorSuratTextFocusLost
//PlaceHolder untuk TextField Fakultas
    private void fakultasTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fakultasTextFocusGained
        if(fakultasText.getText().equals("Fakultas")){
            fakultasText.setText("");
            fakultasText.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_fakultasTextFocusGained

    private void fakultasTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fakultasTextFocusLost
        if(fakultasText.getText().equals("")){
            fakultasText.setText("Fakultas");
            fakultasText.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_fakultasTextFocusLost
//PlaceHolder untuuk TextField Kode Surat
    private void jenisKodeSuratTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jenisKodeSuratTextFocusGained
        if(jenisKodeSuratText.getText().equals("Jenis Kode Surat")){
            jenisKodeSuratText.setText("");
            jenisKodeSuratText.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_jenisKodeSuratTextFocusGained

    private void jenisKodeSuratTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jenisKodeSuratTextFocusLost
         if(jenisKodeSuratText.getText().equals("")){
            jenisKodeSuratText.setText("Jenis Kode Surat");
            jenisKodeSuratText.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jenisKodeSuratTextFocusLost
//PlaceHolder untuk TextField Universitas
    private void universitasTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_universitasTextFocusGained
        if(universitasText.getText().equals("Universitas")){
            universitasText.setText("");
            universitasText.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_universitasTextFocusGained

    private void universitasTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_universitasTextFocusLost
         if(universitasText.getText().equals("")){
            universitasText.setText("Universitas");
            universitasText.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_universitasTextFocusLost
//PlaceHolder untuk TextField Perihal
    private void perihalTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_perihalTextFocusGained
        if(perihalText.getText().equals("Perihal")){
            perihalText.setText("");
            perihalText.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_perihalTextFocusGained

    private void perihalTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_perihalTextFocusLost
        if(perihalText.getText().equals("")){
            perihalText.setText("Perihal");
            perihalText.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_perihalTextFocusLost
//Button Hapus
    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusButtonActionPerformed
        try {
            Connection koneksi = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/arsip_lk","root", "");
            koneksi.createStatement().executeUpdate("delete from suratlk where NomorSurat= '"+nomorSuratText.getText()+"'");
        } catch (SQLException ex) {
            Logger.getLogger(UserInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
        //Pengkondisian Ada tidaknya value pada textfield
            //Prompt
            if(nomorSuratText.getText().equals("Nomor Surat")&&jenisKodeSuratText.getText().equals("Jenis Kode Surat")&&perihalText.getText().equals("Perihal")&&fakultasText.getText().equals("Fakultas")&&universitasText.getText().equals("Universitas")&&bulanText.getText().equals("Bulan")&&tahunText.getText().equals("Tahun")&&keteranganComboBox.getSelectedItem().equals("Umum")){
                JOptionPane.showMessageDialog(this, "Harap pilih data yang ingin dihapus");
            }else if(nomorSuratText.getText().equals("Nomor Surat")||jenisKodeSuratText.getText().equals("Jenis Kode Surat")||perihalText.getText().equals("Perihal")||fakultasText.getText().equals("Fakultas")||universitasText.getText().equals("Universitas")||bulanText.getText().equals("Bulan")||tahunText.getText().equals("Tahun")||keteranganComboBox.getSelectedItem().equals("Umum")){
                JOptionPane.showMessageDialog(this, "Harap pilih data yang ingin diganti");
            }else{
                tampilkanData();
                tampilkanTextFieldUtama();
                timpaWarnaBaruTexFieldFocus();
            }
    }//GEN-LAST:event_hapusButtonActionPerformed
//Button Tambah
    private void tambahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahButtonActionPerformed
        tampilkanData();
        tampilkanTextFieldUtama();
        timpaWarnaBaruTexFieldFocus();
        
        
    }//GEN-LAST:event_tambahButtonActionPerformed
//PlaceHolder untuk TextField Cari Berdasarkan Nomor Surat Text
    private void cariBerdasarkanNomorSuratTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cariBerdasarkanNomorSuratTextFocusGained
        if(cariBerdasarkanNomorSuratText.getText().equals("Cari Berdasarkan Nomor Surat")){
           cariBerdasarkanNomorSuratText.setText("");
           cariBerdasarkanNomorSuratText.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_cariBerdasarkanNomorSuratTextFocusGained

    private void cariBerdasarkanNomorSuratTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cariBerdasarkanNomorSuratTextFocusLost
        if(cariBerdasarkanNomorSuratText.getText().equals("")){
           cariBerdasarkanNomorSuratText.setText("Cari Berdasarkan Nomor Surat");
           cariBerdasarkanNomorSuratText.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_cariBerdasarkanNomorSuratTextFocusLost
//PlaceHolder untuk TextField Cari Berdasarkan Jenis Surat Text
    private void cariBerdasarkanJenisKodeSuratTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cariBerdasarkanJenisKodeSuratTextFocusGained
        if(cariBerdasarkanJenisKodeSuratText.getText().equals("Cari Berdasarkan Jenis Kode Surat")){
           cariBerdasarkanJenisKodeSuratText.setText("");
           cariBerdasarkanJenisKodeSuratText.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_cariBerdasarkanJenisKodeSuratTextFocusGained

    private void cariBerdasarkanJenisKodeSuratTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cariBerdasarkanJenisKodeSuratTextFocusLost
        if(cariBerdasarkanJenisKodeSuratText.getText().equals("")){
           cariBerdasarkanJenisKodeSuratText.setText("Cari Berdasarkan Jenis Kode Surat");
           cariBerdasarkanJenisKodeSuratText.setForeground(new Color(153,153,153));          
        }
    }//GEN-LAST:event_cariBerdasarkanJenisKodeSuratTextFocusLost
//PlaceHolder untuk TextField Cari Berdasarkan Universitas
    private void cariBerdasarkanUniversitasTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cariBerdasarkanUniversitasTextFocusGained
        if(cariBerdasarkanUniversitasText.getText().equals("Cari Berdasarkan Universitas")){
           cariBerdasarkanUniversitasText.setText("");
           cariBerdasarkanUniversitasText.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_cariBerdasarkanUniversitasTextFocusGained

    private void cariBerdasarkanUniversitasTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cariBerdasarkanUniversitasTextFocusLost
        if(cariBerdasarkanUniversitasText.getText().equals("")){
           cariBerdasarkanUniversitasText.setText("Cari Berdasarkan Universitas");
           cariBerdasarkanUniversitasText.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_cariBerdasarkanUniversitasTextFocusLost
//PlaceHolder untuk TextField Cari Berdasarkan Keterangan
    private void cariBerdasarkanKeteranganTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cariBerdasarkanKeteranganTextFocusGained
        if(cariBerdasarkanKeteranganText.getText().equals("Cari Berdasarkan Keterangan")){
           cariBerdasarkanKeteranganText.setText("");
           cariBerdasarkanKeteranganText.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_cariBerdasarkanKeteranganTextFocusGained

    private void cariBerdasarkanKeteranganTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cariBerdasarkanKeteranganTextFocusLost
        if(cariBerdasarkanKeteranganText.getText().equals("")){
           cariBerdasarkanKeteranganText.setText("Cari Berdasarkan Keterangan");
           cariBerdasarkanKeteranganText.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_cariBerdasarkanKeteranganTextFocusLost
//Button Cari(Nomor Surat):
    private void cariBerdasarkanNomorSuratButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariBerdasarkanNomorSuratButtonActionPerformed
        //Pengkondisian Ada tidaknya value pada textfield
            //Prompt
            if(cariBerdasarkanNomorSuratText.getText().equals("Cari Berdasarkan Nomor Surat")){
                JOptionPane.showMessageDialog(this,"Isi textfield terlebih dahulu");
            }else {
                tampilkanTextFieldUtama();
                timpaWarnaBaruTexFieldFocus();
                int row = tabelSurat.getRowCount();
                for(int s = 0; s < row; s++){
                    model.removeRow(0);
                }
                try{
                    Connection koneksi = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/arsip_lk","root", "");
                    ResultSet rs = koneksi.createStatement().executeQuery("select * from suratlk where NomorSurat = '"+cariBerdasarkanNomorSuratText.getText()+"'");
                    while(rs.next()){
                        String data[] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8)};
                        model.addRow(data);
                        cariBerdasarkanNomorSuratText.setText("Cari Berdasarkan Nomor Surat");
                        cariBerdasarkanNomorSuratText.setForeground(new Color(153,153,153));
                    }
                } catch(SQLException ex) {
                    Logger.getLogger(UserInterface.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
    }//GEN-LAST:event_cariBerdasarkanNomorSuratButtonActionPerformed
//Button Cari(Jenis Kode Surat):
    private void cariBerdasarkanKodeSuratButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariBerdasarkanKodeSuratButtonActionPerformed
        //Pengkondisian Ada tidaknya value pada textfield
            //Prompt
            if(cariBerdasarkanJenisKodeSuratText.getText().equals("Cari Berdasarkan Jenis Kode Surat")){
                JOptionPane.showMessageDialog(this,"Isi textfield terlebih dahulu");
            }else {
                tampilkanTextFieldUtama();
                timpaWarnaBaruTexFieldFocus();
                int row = tabelSurat.getRowCount();
                for(int s = 0; s < row; s++){
                    model.removeRow(0);
                }
                try{
                    Connection koneksi = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/arsip_lk","root", "");
                    ResultSet rs = koneksi.createStatement().executeQuery("select * from suratlk where JenisKodeSurat = '"+cariBerdasarkanJenisKodeSuratText.getText()+"'");
                    while(rs.next()){
                        String data[] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8)};
                        model.addRow(data);
                        cariBerdasarkanJenisKodeSuratText.setText("Cari Berdasarkan Jenis Kode Surat");
                        cariBerdasarkanJenisKodeSuratText.setForeground(new Color(153,153,153));
                    }
                } catch(SQLException ex) {
                    Logger.getLogger(UserInterface.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
    }//GEN-LAST:event_cariBerdasarkanKodeSuratButtonActionPerformed
//Button Cari(Universitas):
    private void cariBerdasarkanUniversitasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariBerdasarkanUniversitasButtonActionPerformed
        //Pengkondisian Ada tidaknya value pada textfield
            //Prompt
            if(cariBerdasarkanUniversitasText.getText().equals("Cari Berdasarkan Universitas")){
                JOptionPane.showMessageDialog(this,"Isi textfield terlebih dahulu");
            }else {
                tampilkanTextFieldUtama();
                timpaWarnaBaruTexFieldFocus();
                int row = tabelSurat.getRowCount();
                for(int s = 0; s < row; s++){
                    model.removeRow(0);
                }
                try{
                    Connection koneksi = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/arsip_lk","root", "");
                    ResultSet rs = koneksi.createStatement().executeQuery("select * from suratlk where Universitas = '"+cariBerdasarkanUniversitasText.getText()+"'");
                    while(rs.next()){
                        String data[] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8)};
                        model.addRow(data);
                        cariBerdasarkanUniversitasText.setText("Cari Berdasarkan Universitas");
                        cariBerdasarkanUniversitasText.setForeground(new Color(153,153,153));
                    }
                } catch(SQLException ex) {
                    Logger.getLogger(UserInterface.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        
    }//GEN-LAST:event_cariBerdasarkanUniversitasButtonActionPerformed
//Button Cari(Keterangan):
    private void cariBerdasarkanKeteranganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariBerdasarkanKeteranganButtonActionPerformed
        //Pengkondisian Ada tidaknya value pada textfield
            //Prompt
            if(cariBerdasarkanKeteranganText.getText().equals("Cari Berdasarkan Keterangan")){
                JOptionPane.showMessageDialog(this,"Isi textfield terlebih dahulu");
            }else {
                tampilkanTextFieldUtama();
                timpaWarnaBaruTexFieldFocus();
                int row = tabelSurat.getRowCount();
                for(int s = 0; s < row; s++){
                    model.removeRow(0);
                }
                try{
                    Connection koneksi = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/arsip_lk","root", "");
                    ResultSet rs = koneksi.createStatement().executeQuery("select * from suratlk where Keterangan = '"+cariBerdasarkanKeteranganText.getText()+"'");
                    while(rs.next()){
                        String data[] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8)};
                        model.addRow(data);
                        cariBerdasarkanKeteranganText.setText("Cari Berdasarkan Universitas");
                        cariBerdasarkanKeteranganText.setForeground(new Color(153,153,153));

                    }
                } catch(SQLException ex) {
                    Logger.getLogger(UserInterface.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
    }//GEN-LAST:event_cariBerdasarkanKeteranganButtonActionPerformed
//PlaceHolder untuk TextField Bulan
    private void bulanTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bulanTextFocusGained
        if(bulanText.getText().equals("Bulan")){
            bulanText.setText("");
            bulanText.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_bulanTextFocusGained

    private void bulanTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bulanTextFocusLost
        if(bulanText.getText().equals("")){
            bulanText.setText("Bulan");
            bulanText.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_bulanTextFocusLost
//PlaceHolder untuk TextField Tahun
    private void tahunTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tahunTextFocusGained
        if(tahunText.getText().equals("Tahun")){
            tahunText.setText("");
            tahunText.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_tahunTextFocusGained

    private void tahunTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tahunTextFocusLost
        if(tahunText.getText().equals("")){
            tahunText.setText("Tahun");
            tahunText.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_tahunTextFocusLost

    private void formatTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formatTextFocusGained
        //
    }//GEN-LAST:event_formatTextFocusGained

    private void formatTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formatTextFocusLost
        //
    }//GEN-LAST:event_formatTextFocusLost

    private void tanggalSuratTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tanggalSuratTextFocusGained
        //
    }//GEN-LAST:event_tanggalSuratTextFocusGained

    private void tanggalSuratTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tanggalSuratTextFocusLost
        //
    }//GEN-LAST:event_tanggalSuratTextFocusLost

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        new pageLogin().setVisible(true); 
    }//GEN-LAST:event_logOutButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args
     */
//Main    
    public static void main(String args[]) {
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //menampilkan semua metod dan design
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new UserInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bulanText;
    private javax.swing.JTextField cariBerdasarkanJenisKodeSuratText;
    private javax.swing.JButton cariBerdasarkanKeteranganButton;
    private javax.swing.JTextField cariBerdasarkanKeteranganText;
    private javax.swing.JButton cariBerdasarkanKodeSuratButton;
    private javax.swing.JButton cariBerdasarkanNomorSuratButton;
    private javax.swing.JTextField cariBerdasarkanNomorSuratText;
    private javax.swing.JButton cariBerdasarkanUniversitasButton;
    private javax.swing.JTextField cariBerdasarkanUniversitasText;
    private javax.swing.JButton exitButton;
    private javax.swing.JTextField fakultasText;
    private javax.swing.JTextField formatText;
    private javax.swing.JButton gantiButton;
    private javax.swing.JButton hapusButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jenisKodeSuratText;
    private javax.swing.JComboBox keteranganComboBox;
    private javax.swing.JButton logOutButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField nomorSuratText;
    private javax.swing.JTextField perihalText;
    private javax.swing.JButton simpanButton;
    private javax.swing.JTable tabelSurat;
    private javax.swing.JTextField tahunText;
    private javax.swing.JButton tambahButton;
    private javax.swing.JTextField tanggalSuratText;
    private javax.swing.JTextField universitasText;
    // End of variables declaration//GEN-END:variables
//Method Tampilkan
    private void tampilkanData() {
        int row = tabelSurat.getRowCount();
        for(int s = 0; s < row; s++){
            model.removeRow(0);
        }
        try{
            Connection koneksi = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/arsip_lk","root", "");
            ResultSet rs = koneksi.createStatement().executeQuery("select * from suratlk");
            while(rs.next()){
                String data[] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8)};
                model.addRow(data);
            }
        } catch(SQLException ex) {
            Logger.getLogger(UserInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
//Method SetText to TextField
    private void tampilkanTextFieldUtama() {
        //menampilkan Value TextField Utama
        nomorSuratText.setText("Nomor Surat");
        jenisKodeSuratText.setText("Jenis Kode Surat");
        perihalText.setText("Perihal");
        fakultasText.setText("Fakultas");
        universitasText.setText("Universitas");
        bulanText.setText("Bulan");
        tahunText.setText("Tahun");
        formatText.setText("");
        tanggalSuratText.setText("");
        nomorSuratText.setEditable(false);
        formatText.setEditable(false);
        tanggalSuratText.setEditable(false);
    }
//Method SetForeground Color for TextField 
    private void timpaWarnaBaruTexFieldFocus() {
        //menimpa warna baru untuk TextFieldFocus
        nomorSuratText.setForeground(new Color(153,153,153));
        jenisKodeSuratText.setForeground(new Color(153,153,153));
        perihalText.setForeground(new Color(153,153,153));
        fakultasText.setForeground(new Color(153,153,153));
        universitasText.setForeground(new Color(153,153,153));
        bulanText.setForeground(new Color(153,153,153));
        tahunText.setForeground(new Color(153,153,153));
    }
//Method Lebar Kolom Tabel    
    private void lebarKolom(){ 
        TableColumn column;
        tabelSurat.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        //Kolom Nomor Surat
        column = tabelSurat.getColumnModel().getColumn(0); 
        column.setPreferredWidth(75);
        //Kolom Jenis Kode Surat
        column = tabelSurat.getColumnModel().getColumn(1); 
        column.setPreferredWidth(150); 
        //Kolom Perihal
        column = tabelSurat.getColumnModel().getColumn(2); 
        column.setPreferredWidth(125); 
        //Kolom Fakultas
        column = tabelSurat.getColumnModel().getColumn(3); 
        column.setPreferredWidth(75); 
        //Kolom Universitas
        column = tabelSurat.getColumnModel().getColumn(4); 
        column.setPreferredWidth(175); 
        //Kolom Bulan
        column = tabelSurat.getColumnModel().getColumn(5); 
        column.setPreferredWidth(100); 
        //Kolom Tahun
        column = tabelSurat.getColumnModel().getColumn(6); 
        column.setPreferredWidth(150); 
        //Kolom Keterangan
        column = tabelSurat.getColumnModel().getColumn(7); 
        column.setPreferredWidth(268); 
    }
}
